driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  #
  # database-test
  #
  - name: mysql
    run_list:
    - recipe[mysql_database_test]
  - name: postgresql
    run_list:
    - recipe[postgresql_database_test]
  - name: sqlite
    run_list:
    - recipe[sqlite_database_test]
